# -*- coding: utf-8 -*-
"""gui_skripsi.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g5nW3iKZHMvmuE4oNO2kff0_2dh5vp2C
"""

import streamlit as st
import pandas as pd
import joblib

# ==============================
# Konfigurasi Awal
# ==============================
st.set_page_config(
    page_title="Prediksi TAM Multilabel dengan SVM",
    page_icon="🌿",
    layout="wide",
)

# ==============================
# Load Model
# ==============================
import joblib
import os

# Tentukan path relatif
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
MODEL_PATH = os.path.join(BASE_DIR, "svm_tam_model.pkl")
VECTORIZER_PATH = os.path.join(BASE_DIR, "tfidf_vectorizer.pkl")

# Load model dan vectorizer
svm_model = joblib.load(MODEL_PATH)
vectorizer = joblib.load(VECTORIZER_PATH)

kolom_aspek = ["PU", "PEOU", "Attitude", "Intention", "ActualUse"]

# ==============================
# Tampilan Header
# ==============================
st.markdown(
    """
    <style>
    .main {
        background-color: #F8FAFC;
        padding: 20px;
        border-radius: 10px;
    }
    h1, h2, h3 {
        color: #1E3A8A;
    }
    .stButton>button {
        background-color: #1E3A8A;
        color: white;
        border-radius: 8px;
        padding: 0.6em 1.2em;
        border: none;
    }
    .stButton>button:hover {
        background-color: #3B82F6;
        color: white;
    }
    </style>
    """,
    unsafe_allow_html=True
)

st.markdown("<h1 style='text-align: center;'> Prediksi Aspek TAM Menggunakan SVM </h1>", unsafe_allow_html=True)
st.markdown("<p style='text-align:center;'>Masukkan ulasan atau unggah file CSV untuk memprediksi aspek TAM (PU, PEOU, Attitude, Intention, Actual Use).</p>", unsafe_allow_html=True)
st.write("---")

# ==============================
# Sidebar Navigasi
# ==============================
st.sidebar.header("📊 Menu Navigasi")
menu = st.sidebar.radio("Pilih Mode:", ["Prediksi Manual", "Prediksi dari File CSV"])

# ==============================
# Mode 1: Prediksi Manual
# ==============================
if menu == "Prediksi Manual":
    st.subheader("📝 Prediksi dari Teks Manual")

    ulasan = st.text_area("Masukkan ulasan pengguna:", height=150)

    if st.button("Prediksi Sekarang"):
        if ulasan.strip():
            X_input = vectorizer.transform([ulasan])
            y_pred = svm_model.predict(X_input)[0]
            hasil = {kolom_aspek[i]: int(y_pred[i]) for i in range(len(kolom_aspek))}

            st.markdown(
                """
                <div style='background-color:#1E3A8A; padding:12px; border-radius:8px; color:white;'>
                    <h3 style='text-align:center;'> Hasil Prediksi Aspek TAM </h3>
                </div>
                """,
                unsafe_allow_html=True
            )

            st.json(hasil)

            terdeteksi = [k for k, v in hasil.items() if v == 1]

            if terdeteksi:
                st.markdown(
                    f"""
                    <div style='background-color:#E0E7FF; color:#1E3A8A; padding:12px; border-radius:8px; text-align:center;'>
                        <h4> Aspek TAM yang terdeteksi:</h4>
                        <b>{', '.join(terdeteksi)}</b>
                    </div>
                    """,
                    unsafe_allow_html=True
                )
            else:
                st.markdown(
                    """
                    <div style='background-color:#F3F4F6; color:#1E3A8A; padding:12px; border-radius:8px; text-align:center;'>
                        <h4> Tidak ada aspek TAM yang terdeteksi.</h4>
                    </div>
                    """,
                    unsafe_allow_html=True
                )
        else:
            st.warning("Masukkan ulasan terlebih dahulu!")

# ==============================
# Mode 2: Prediksi CSV
# ==============================
elif menu == "Prediksi dari File CSV":
    st.subheader("📂 Prediksi dari File CSV")

    uploaded_file = st.file_uploader("Upload file CSV ulasan", type=["csv"])
    if uploaded_file is not None:
        try:
            data = pd.read_csv(uploaded_file, encoding="utf-8")
        except UnicodeDecodeError:
            uploaded_file.seek(0)
            data = pd.read_csv(uploaded_file, encoding="latin1")

        if "ulasan" in data.columns:
            with st.spinner("🔍 Sedang memproses prediksi..."):
                X = vectorizer.transform(data["ulasan"].astype(str))
                preds = svm_model.predict(X)
                pred_df = pd.DataFrame(preds, columns=kolom_aspek)
                hasil = pd.concat([data, pred_df], axis=1)

            st.markdown(
                """
                <div style='background-color:#1E3A8A; color:white; padding:12px; border-radius:8px; text-align:center;'>
                     <b>Prediksi berhasil!</b>
                </div>
                """,
                unsafe_allow_html=True
            )

            st.dataframe(hasil)

            csv = hasil.to_csv(index=False).encode("utf-8")
            st.download_button(
                label="⬇️ Download Hasil Prediksi",
                data=csv,
                file_name="hasil_prediksi.csv",
                mime="text/csv",
            )
        else:
            st.error("CSV harus punya kolom bernama **'ulasan'**")
